// Legal copy for PaperMind, rendered by pages/LegalPage.jsx via react-markdown.
//
// PLACEHOLDERS to fill before going live (search for "[[" ):
//   [[OPERATOR]]    legal entity or individual operating PaperMind
//   [[JURISDICTION]] governing-law jurisdiction (e.g. "England and Wales")
//   [[CONTACT_EMAIL]] support / legal contact address
// These are intentionally left as bracketed tokens so they're easy to grep
// and so the docs never silently ship with the wrong name on them.

export const EFFECTIVE_DATE = 'June 18, 2026'

const OPERATOR = '[[OPERATOR]]'
const JURISDICTION = '[[JURISDICTION]]'
const CONTACT = '[[CONTACT_EMAIL]]'

export const TERMS_MD = `# Terms of Service

**Effective ${EFFECTIVE_DATE}**

These Terms of Service ("Terms") govern your access to and use of PaperMind
(the "Service"), operated by ${OPERATOR} ("we", "us", "our"). By creating an
account or using the Service you agree to these Terms. If you do not agree, do
not use the Service.

## 1. The Service

PaperMind lets you upload research documents (PDFs) and ask questions about
them. Answers are generated by automated systems and large language models and
are intended to cite the source passages they draw from.

**The Service is an assistance tool, not a source of professional advice.**
Generated answers may be incomplete, out of date, or wrong, and may
occasionally misattribute or omit a citation. You are responsible for
independently verifying any answer before relying on it. Nothing produced by
the Service constitutes legal, medical, financial, academic, or other
professional advice.

## 2. Eligibility and accounts

You must be at least 16 years old (or the age of digital consent in your
jurisdiction, if higher) to use the Service. Accounts are created and
authenticated through our identity provider (Clerk). You are responsible for
the activity that occurs under your account and for keeping your login
credentials secure.

## 3. Your content and upload rights

You retain ownership of the documents and text you upload ("Your Content").

**You are solely responsible for ensuring you have the rights to upload and
process Your Content.** By uploading a document you represent and warrant that
you own it or have the necessary licenses, permissions, and rights to upload it
and to have it processed as described in these Terms and our Privacy Policy, and
that doing so does not infringe any third party's copyright, contract, or other
rights. Many research papers are copyrighted; uploading a paper you do not have
the right to use is your responsibility, not ours.

You grant us a limited, worldwide, non-exclusive license to store, copy,
transmit, and process Your Content **solely** to operate and provide the
Service to you — including sending document text to the third-party model
providers listed in our Privacy Policy so they can generate answers. We do not
use Your Content to train our own models. We do not claim ownership of Your
Content.

## 4. Acceptable use

You agree not to:

- upload content you do not have the right to upload, or that is unlawful,
  infringing, or malicious;
- use the Service to violate any law or third-party right;
- attempt to circumvent quotas, rate limits, authentication, or other
  technical restrictions;
- probe, scan, overload, or disrupt the Service or its infrastructure, or
  attempt to access data that is not yours;
- resell, sublicense, or build a competing service by scraping or bulk-
  extracting the Service's outputs.

We may suspend or terminate accounts that violate this section.

## 5. Plans, quotas, and billing

The Service offers a **Free** plan (subject to usage quotas — currently 3
papers and 20 queries per month) and a **Pro** plan (currently $9 per month for
unlimited papers and queries). Current limits and prices are shown in the app
and may change on reasonable notice.

Paid subscriptions are handled by **Stripe**. By subscribing you authorize us,
through Stripe, to charge your payment method on a recurring monthly basis until
you cancel. You can cancel at any time through the customer billing portal;
cancellation takes effect at the end of the current billing period. Except where
required by law, payments are non-refundable. We do not store your full card
details — they are handled directly by Stripe.

## 6. Disclaimers

THE SERVICE IS PROVIDED "AS IS" AND "AS AVAILABLE", WITHOUT WARRANTIES OF ANY
KIND, EXPRESS OR IMPLIED, INCLUDING WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
PARTICULAR PURPOSE, NON-INFRINGEMENT, AND ANY WARRANTY THAT GENERATED ANSWERS
ARE ACCURATE, COMPLETE, OR RELIABLE. We do not warrant that the Service will be
uninterrupted, secure, or error-free.

## 7. Limitation of liability

TO THE MAXIMUM EXTENT PERMITTED BY LAW, ${OPERATOR} WILL NOT BE LIABLE FOR ANY
INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR EXEMPLARY DAMAGES, OR FOR ANY
LOSS OF DATA, PROFITS, OR GOODWILL, ARISING OUT OF OR RELATING TO YOUR USE OF
THE SERVICE. OUR TOTAL AGGREGATE LIABILITY FOR ANY CLAIM RELATING TO THE SERVICE
WILL NOT EXCEED THE GREATER OF (A) THE AMOUNTS YOU PAID US IN THE 12 MONTHS
BEFORE THE CLAIM AROSE, OR (B) USD $50.

## 8. Termination

You may stop using the Service and delete your account at any time. We may
suspend or terminate your access if you breach these Terms or if we discontinue
the Service. On account deletion, Your Content is removed as described in the
Privacy Policy.

## 9. Changes to these Terms

We may update these Terms from time to time. If we make material changes we will
update the effective date above and, where appropriate, notify you in the app.
Continued use after changes take effect constitutes acceptance.

## 10. Governing law

These Terms are governed by the laws of ${JURISDICTION}, without regard to its
conflict-of-laws rules, and you agree to the exclusive jurisdiction of its
courts, except where mandatory local consumer-protection law provides otherwise.

## 11. Contact

Questions about these Terms? Contact us at ${CONTACT}.
`

export const PRIVACY_MD = `# Privacy Policy

**Effective ${EFFECTIVE_DATE}**

This Privacy Policy explains what information PaperMind (the "Service"), operated
by ${OPERATOR}, collects, how we use it, and who we share it with. It should be
read together with our Terms of Service.

## 1. Information we collect

**Account information.** When you sign up we receive your email address, name,
and authentication identifiers from our identity provider, Clerk. We do not see
or store your password.

**Documents you upload.** The PDFs you upload, the text extracted from them, and
the vector embeddings and metadata derived from that text, so we can index and
answer questions about them.

**Usage information.** Your queries, and per-request operational data such as the
number of model calls, token counts, and estimated cost, which we use to enforce
quotas and understand cost. We also collect basic product-analytics and
error-diagnostic data (see "Analytics and error tracking" below).

**Payment information.** If you subscribe, your payment is processed by Stripe.
We receive subscription status and a Stripe customer identifier; **we do not
store your full payment-card details** — Stripe handles them directly.

## 2. How we use your information

We use the information above to: provide and operate the Service (indexing your
documents and generating answers); authenticate you; enforce plan quotas; process
payments; monitor, debug, and improve reliability and performance; and comply
with legal obligations. **We do not sell your personal information, and we do not
use your uploaded documents to train our own models.**

## 3. Service providers and subprocessors

To run the Service we share data with the following processors, each only as
needed for their function:

| Provider | Purpose | Data shared |
|---|---|---|
| Clerk | Authentication | Account identifiers, email |
| Neon (Postgres) | Document & usage metadata | Paper records, usage events |
| Cloudflare R2 | Document storage | Your uploaded PDFs |
| Stripe | Payments | Email, subscription & customer IDs |
| Groq, Google (Gemini), Mistral, Cerebras | Answer generation | **Text from your documents and your queries** |
| Sentry | Error tracking | Diagnostic error data |
| PostHog | Product analytics | Pseudonymous usage events |
| Hosting providers (e.g. Hugging Face, Vercel) | Running the app | Request data |

**Important:** to answer your questions, passages from your uploaded documents
and your query text are sent to the third-party large-language-model providers
listed above for processing. Their handling of that data is governed by their own
terms and privacy policies. Do not upload documents whose contents you are not
permitted to disclose to such third-party processors.

## 4. Analytics and error tracking

We use Sentry to capture application errors and PostHog to understand how the
product is used. Analytics events are tied only to your pseudonymous account
identifier, not to your name or the contents of your documents. These services
are optional infrastructure and can be disabled by the operator.

## 5. Data retention and deletion

Your uploaded documents and their derived data are retained while your account is
active. When you delete a paper, we delete its stored PDF and its database record;
its search index is regenerable and is not a separate copy of your content. When
you delete your account, we delete the documents and metadata associated with it,
except where we must retain limited records (e.g. billing history) to meet legal
or accounting obligations. Backups and third-party processor logs may persist for
a limited period before being overwritten.

## 6. Security

We use authentication, per-user data scoping, encrypted transport, and access
controls to protect your data. No system is perfectly secure, and we cannot
guarantee absolute security.

## 7. Your rights

Depending on your jurisdiction, you may have the right to access, correct,
export, or delete your personal information, or to object to or restrict certain
processing. You can delete your papers and account in the app, or contact us at
${CONTACT} to exercise these rights.

## 8. International transfers

Our providers may process data in countries other than yours. Where required, we
rely on appropriate safeguards for such transfers.

## 9. Children

The Service is not directed to children under 16, and we do not knowingly collect
their personal information.

## 10. Changes to this policy

We may update this policy from time to time. Material changes will be reflected
in the effective date above and, where appropriate, announced in the app.

## 11. Contact

Questions about your privacy or this policy? Contact us at ${CONTACT}.
`
